1. select len(null),len(' hello '),len('');
2. select lower('FNAME'),upper('fname');
3. select substring('jaynhnblk',1,3);
4. select substring('jaynhnblkfjsdklj',3,10);
5. select replace('abc123efg','123','XYZ'),replace('abcabcabc','c','5');
6. select ascii('a'),ascii('A'),ascii('z'),ascii('Z'),ascii(0),ascii(9);
7. select char(97),char(65),char(122),char(90),char(48),char(57);
8. select ltrim('   hello world   ');
9. select rtrim('      hello world   ');
10.select left('sql server',4),right('sql server',5);
11.select cast(1234.56 as int);
   select convert(int,1234.56);
12.select cast(10.58 as int);
   select convert(int,10.58);
13.select space(10)+'anyname';
14.select 'write'+'your name';
   select concat('hello','world');
15.select reverse('darshan');
16.select replicate('your name',3);